### ISSUE TITLE
how to install and run your project?

### ISSUE THREAD

**Issue by ChaosBee** [alexemorris/nba-heatmap#1]
Hi, I am a NBA fan and curious about _Data Visualization_.
I want to know how to run your project. I have a problem with installing such modules as **secret** and **psycopg2**

**Comment by alexemorris** [comment]
Hi,
This project is a bit dead at the moment. However I am planning on going back to it at some point in the next few months, when I do I'll be sure to help you out! Right now there's far too much to fix.

I will keep you posted,
Alex

**Comment by ChaosBee** [comment]
@alexemorris  Thanks for your effort.
